name: First-GitHub-action
env:
  APPLICATION_NAME   : "MyFlask"
  DEPLOY_PACKAGE_NAME: "flask-deploy-ver-${{github.sha}}"

on:
  push:
    branches:
      - main

jobs:
  job_testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello Message in Testing
      run: echo "Hello World from Testing job"
    - name: Execute few commands
      run: |
        echo "Hello Message1"
        echo "Hello Message2"
        echo "Application name: ${{env.APPLICATION_NAME}}"
    - name: Git clone my repo
      uses: actions/checkout@v1
    - name: List current folder
      run: ls -la

  job_deploy:
    runs-on: ubuntu-latest
    needs: [job_testing]
    env:
      VAR1: "This is Job Level Variable 1"
      VAR2: "This is Job Level Variable 2"
    
    steps:
    - name: Print Hello Message in Deploy
      run: echo "Hello World from Deploy job"
    - name: Print env vars
      run: |
        echo "Var1 = ${{env.VAR1}}"
        echo "Var2 = ${{env.VAR2}}"
        echo "Var3 = $LOCAL_VAR"
      env:
        LOCAL_VAR: "Local var from Print env vars"
    - name: Printing Deployment package
      run: echo "Deploy package name is ${{env.DEPLOY_PACKAGE_NAME}}"
    - name: Lets test aws here
      run: aws --version
    - name: Lets test zip here
      run: zip --version
